-- Habit Tracker: per-user habits table
--
-- How to run this: Supabase Dashboard -> SQL Editor -> paste this whole file -> Run.
-- Safe to run once. Re-running will error on "table already exists" (expected).

create table public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  completed_dates text[] not null default '{}',
  postponed_dates text[] not null default '{}',
  created_at timestamptz not null default now()
);

create index habits_user_id_idx on public.habits(user_id);

alter table public.habits enable row level security;

create policy "Users can view their own habits" on public.habits
  for select using (auth.uid() = user_id);

create policy "Users can insert their own habits" on public.habits
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own habits" on public.habits
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can delete their own habits" on public.habits
  for delete using (auth.uid() = user_id);
